---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  labels:
    app.kubernetes.io/name: pinger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pinger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinger
    spec:
      containers:
      - name: pinger
        image: c8n.io/bmutziu/silly-demo:1.5.2
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        env: 
          - name: SERVICE_NAME
            value: pinger
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.observability:14268/api/traces
