image:
  repository: c8n.io/vfarcic/silly-demo
  tag: 1.6.4
ingress:
  host: bmutziu.me
db:
  enabled: true
postgresql:
  global:
    persistence:
      enabled: false
  auth:
    postgresPassword: postgres
  primary:
    initdb:
      scripts:
        00_init_script.sh: |
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -U postgres -c 'CREATE DATABASE "silly-demo";'
schemahero:
  enabled: false
