apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cosign
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
            - Pod
            - Deployment
      verifyImages:
      - imageReferences:
        - "docker.io/bmutziu/silly-demo:*"
        - "c8n.io/bmutziu/silly-demo:*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIpcC5aPlFRXn2PJ7gcpTCqHlj/wJ
                xXF6uvzzBfJVkVZcEenGb7cvrExgbfDaMBdzn4BtVQjuDkGHbdehWwrCQQ==
                -----END PUBLIC KEY-----
