name: ci
run-name: ci
on:
  push:
    branches:
      - main
      - master
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: xxx1
        run: |
          ls -la
          pwd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c8n.io
          username: ${{ secrets.C8N_USER }}
          password: ${{ secrets.C8N_SECRET }}
      - name: Update files
        run: |
          cat Dockerfile | sed -e "s@ENV VERSION .*@ENV VERSION $VERSION@g" | tee Dockerfile.tmp
          mv Dockerfile.tmp Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: c8n.io/vfarcic/silly-demo:latest,c8n.io/vfarcic/silly-demo:1.3.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.0.5
      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY c8n.io/vfarcic/silly-demo:1.3.${{ github.run_number }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: xxx2
        run: |
          ls -la
          pwd
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Package with Timoni
        run: |
          ls -la
          pwd
          yq --inplace ".values.image.tag = \"1.3.${{ github.run_number }}\"" timoni/values.yaml
          cat timoni/values.cue | sed -e "s@image: tag:.*@image: tag: \"1.3.${{ github.run_number }}\"@g" | tee timoni/values.cue.tmp
          mv timoni/values.cue.tmp timoni/values.cue
          timoni mod push timoni oci://c8n.io/vfarcic/silly-demo-package --version 1.3.${{ github.run_number }}
