name: ci
run-name: ci
on:
  push:
    branches:
      - main
      - master
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c8n.io
          username: ${{ secrets.C8N_USER }}
          password: ${{ secrets.C8N_SECRET }}
      - name: Update files
        run: |
          cat Dockerfile | sed -e "s@ENV VERSION .*@ENV VERSION $VERSION@g" | tee Dockerfile.tmp
          mv Dockerfile.tmp Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: c8n.io/vfarcic/silly-demo:latest,c8n.io/vfarcic/silly-demo:1.3.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
